/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef , useEffect} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'


const Model1 = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/new.glb')
  const { actions } = useAnimations(animations, group)

  console.log(Object.keys(actions));
  useEffect(() => {
    if (actions && props.animationName && actions[props.animationName]) {
     actions[props.animationName].reset().play()
    }
  }, [actions, props.animationName])

// useEffect(() => {
//     if (actions && props.animationName && actions[props.animationName]) {
//       actions[props.animationName].reset().fadeIn(0.5).play();
//     } else {
//       console.warn("Animation not found:", props.animationName);
//     }
//   }, [actions, props.animationName]);

  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <skinnedMesh
            name="Body"
            geometry={nodes.Body.geometry}
            material={materials.Bodymat}
            skeleton={nodes.Body.skeleton}
          />
          <skinnedMesh
            name="Bottoms"
            geometry={nodes.Bottoms.geometry}
            material={materials.Bottommat}
            skeleton={nodes.Bottoms.skeleton}
          />
          <skinnedMesh
            name="Eyelashes"
            geometry={nodes.Eyelashes.geometry}
            material={materials.Eyelashmat}
            skeleton={nodes.Eyelashes.skeleton}
          />
          <skinnedMesh
            name="Eyes"
            geometry={nodes.Eyes.geometry}
            material={materials.Bodymat}
            skeleton={nodes.Eyes.skeleton}
          />
          <skinnedMesh
            name="Hair"
            geometry={nodes.Hair.geometry}
            material={materials.Hairmat}
            skeleton={nodes.Hair.skeleton}
          />
          <skinnedMesh
            name="Shoes"
            geometry={nodes.Shoes.geometry}
            material={materials.Shoesmat}
            skeleton={nodes.Shoes.skeleton}
          />
          <skinnedMesh
            name="Tops"
            geometry={nodes.Tops.geometry}
            material={materials.Topmat}
            skeleton={nodes.Tops.skeleton}
          />
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/new.glb')
export default Model1